
INSERT INTO TASKS(T_ID, T_NAME, DURATION) VALUES (1, 'Homepage Design', 15);
INSERT INTO TASKS(T_ID, T_NAME, DURATION) VALUES (2, 'Social Media Post Design', 6);
INSERT INTO TASKS(T_ID, T_NAME, DURATION) VALUES (3, 'Contact client', 3);
INSERT INTO TASKS(T_ID, T_NAME, DURATION) VALUES (4, 'Develop landing page', 35);
INSERT INTO TASKS(T_ID, T_NAME, DURATION) VALUES (5, 'Publsihing AD video', 45);

INSERT INTO EMPLOYEES(EMP_ID, EMP_NAME, POSITION, HOURS) VALUES ( 1, 'Khanim Huseynzada', 'Graphic Designer', '8:00-12:00' );
INSERT INTO EMPLOYEES(EMP_ID, EMP_NAME, POSITION, HOURS) VALUES ( 2, 'Narmina Aghayeva', 'Web Designer', '10:00-19:00' );
INSERT INTO EMPLOYEES(EMP_ID, EMP_NAME, POSITION, HOURS) VALUES ( 3, 'Nazrin Ibrahimli', 'IOS Developer' , '10:00-18:00');
INSERT INTO EMPLOYEES(EMP_ID, EMP_NAME, POSITION, HOURS) VALUES ( 4, 'Kamran Hasan', 'Web Developer' , '10:00-18:00');
INSERT INTO EMPLOYEES(EMP_ID, EMP_NAME, POSITION, HOURS) VALUES ( 5, 'Ali Safarli', 'Video editor' , '11:00-18:00');
INSERT INTO EMPLOYEES(EMP_ID, EMP_NAME, POSITION, HOURS) VALUES ( 6, 'Sofia Balayeva', 'Sales Manager' , '9:00-17:00');


INSERT INTO ASSIGNED(EMP_ID, T_ID) VALUES ( 2,1 );
INSERT INTO ASSIGNED(EMP_ID, T_ID) VALUES ( 1,2 );
INSERT INTO ASSIGNED(EMP_ID, T_ID) VALUES ( 4,4 );
INSERT INTO ASSIGNED(EMP_ID, T_ID) VALUES ( 6,3 );
INSERT INTO ASSIGNED(EMP_ID, T_ID) VALUES ( 5,5 );