-- DROP TABLE TEAMS_PLAYERS;
INSERT INTO TEAM VALUES(1, 'Chelsea');
INSERT INTO TEAM VALUES(2, 'Manchester City');
INSERT INTO TEAM VALUES(3, 'Borussia Dortmund');
INSERT INTO TEAM VALUES(4, 'Real Madrid');
INSERT INTO TEAM VALUES(5, 'Barcelona');

INSERT INTO PLAYER VALUES(1, 'Christian', 'Pulisic');
INSERT INTO PLAYER VALUES(2, 'Gabriel', 'Jesus');
INSERT INTO PLAYER VALUES(3, 'Jadon', 'Sancho');
INSERT INTO PLAYER VALUES(4, 'Eden', 'Hazard');
INSERT INTO PLAYER VALUES(5, 'Lionel', 'Messi');
INSERT INTO PLAYER VALUES(6, 'Kai', 'Havertz');

INSERT INTO TEAMS_PLAYERS VALUES (1, 1);
INSERT INTO TEAMS_PLAYERS VALUES (2, 2);
INSERT INTO TEAMS_PLAYERS VALUES (3, 3);
INSERT INTO TEAMS_PLAYERS VALUES (4, 4);
INSERT INTO TEAMS_PLAYERS VALUES (5, 5);
INSERT INTO TEAMS_PLAYERS VALUES (1, 6);