
INSERT INTO BOOKS(BOOK_NAME, PUB_DATE) VALUES ('1984', '01.01.1948');
INSERT INTO BOOKS(BOOK_NAME, PUB_DATE) VALUES ('To Kill a Mockingbird', '11.07.1960');
INSERT INTO BOOKS(BOOK_NAME, PUB_DATE) VALUES ('Love and Prejudice', '12.05.2000');
INSERT INTO BOOKS(BOOK_NAME, PUB_DATE) VALUES ('Greenwood', '21.07.1760');
INSERT INTO BOOKS(BOOK_NAME, PUB_DATE) VALUES ('Canavar', '12.07.2007');

INSERT INTO AUTHORS(BIRTH_DATE, AUTHOR_NAME) VALUES ('01.01.1951', 'Elnur');
INSERT INTO AUTHORS(BIRTH_DATE, AUTHOR_NAME) VALUES ('02.02.1952', 'Jack');
INSERT INTO AUTHORS(BIRTH_DATE, AUTHOR_NAME) VALUES ('03.03.1953', 'Emma');


INSERT INTO PUBLISHMENT(A_ID, B_ID) VALUES (1 ,1);
INSERT INTO PUBLISHMENT(A_ID, B_ID) VALUES (1 ,2);
INSERT INTO PUBLISHMENT(A_ID, B_ID) VALUES (2 ,3);
INSERT INTO PUBLISHMENT(A_ID, B_ID) VALUES (2 ,4);
INSERT INTO PUBLISHMENT(A_ID, B_ID) VALUES (3 ,5);




