-- DROP TABLE TEAMS_PLAYERS;
INSERT INTO TEAM VALUES(1, 1905, 'Chelsea');
INSERT INTO TEAM VALUES(2, 1880, 'Manchester City');
INSERT INTO TEAM VALUES(3, 1909, 'Borussia Dortmund');
INSERT INTO TEAM VALUES(4, 1902, 'Real Madrid');
INSERT INTO TEAM VALUES(5, 1899, 'Barcelona');

INSERT INTO PLAYER VALUES(1, 22, 'Christian', 'Pulisic');
INSERT INTO PLAYER VALUES(2, 24, 'Gabriel', 'Jesus');
INSERT INTO PLAYER VALUES(3, 21, 'Jadon', 'Sancho');
INSERT INTO PLAYER VALUES(4, 30, 'Eden', 'Hazard');
INSERT INTO PLAYER VALUES(5, 34, 'Lionel', 'Messi');
INSERT INTO PLAYER VALUES(6, 21, 'Kai', 'Havertz');

INSERT INTO TEAMS_PLAYERS VALUES (1, 1);
INSERT INTO TEAMS_PLAYERS VALUES (2, 2);
INSERT INTO TEAMS_PLAYERS VALUES (3, 3);
INSERT INTO TEAMS_PLAYERS VALUES (4, 4);
INSERT INTO TEAMS_PLAYERS VALUES (5, 5);
INSERT INTO TEAMS_PLAYERS VALUES (1, 6);