INSERT INTO GAME(ID, NAME) VALUES(3, 'CAR 3');

INSERT INTO ENROLLMENTS (ID, GAME_ID,GAMER_ID) VALUES(1,3,3);

INSERT INTO GAMER(GAMER_ID, NAME) VALUES(3, 'CAR 3');
INSERT INTO USERS VALUES ('leyla', '$2a$08$CiiFQ0/J3PZG8pTWM7z4s.sLEigHCdM5HQhXeRc30wneAOCqhCx0m', true);
INSERT INTO AUTHORITIES values ('leyla', 'ROLE_ADMIN');
